name: Generate webp

on:
  workflow_dispatch:

jobs:
  add_webp:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Generate WEBP files ğŸ–¼ï¸
        run: |
          sudo apt-get install imagemagick graphicsmagick libpng-dev
          npm install
          npm run webp

      - name: Commit Images ğŸš€
        uses: EndBug/add-and-commit@v7
        with:
          message: "Auto add images"
