name: Generate short_link

on:
  workflow_dispatch:

jobs:
  add_short_url:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Generate Shortlinks files ğŸ–¼ï¸
        run: |
          npm install
          npm run generate-url-shortener

      - name: Commit Posts ğŸš€
        uses: EndBug/add-and-commit@v7
        with:
          message: "Auto add short_url"
